import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Mantine CSS imports (load first)
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';

// Custom CSS (load after Mantine to override)
import "./globals.css";
import 'remixicon/fonts/remixicon.css';

import { MantineProvider } from "@mantine/core";
import { theme } from "@/styles/theme";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <MantineProvider theme={theme} defaultColorScheme="light" cssVariablesSelector=":root">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
